### ISSUE TITLE
Front Camera Issue (Not Capturing)

### ISSUE THREAD

**Issue by shivam2702** [Fotoapparat/Fotoapparat#3]
In some devices i faced an issue that its not capturing the Photo by the front camera. 

Ex: One Plus 2 etc...

Sorry for no logs as its not showing any.

**Comment by Diolor** [comment]
Hi @shivam2702, was it API 21+ ? 
Also did any of the following was the case: rotate the activity, had another take request before, or low light?

**Comment by shivam2702** [comment]
API Level was 23 (Android M)
No everything was fine best light first request and portrait.

**Comment by dmitry-zaitsev** [comment]
We are able to reproduce the issue. Fix will come soon.

**Comment by Diolor** [comment]
This issue is now fixed 👍

**Comment by shivam2702** [comment]
Thanks 🥇  you are awesome....

**Comment by dmitry-zaitsev** [comment]
Still an issue for Samsung S7 Edge. Did not try on Moto G3 yet.

**Comment by Diolor** [comment]
Default FA configuration in sample app? Sorry cannot reproduce in my 6P

**Comment by dmitry-zaitsev** [comment]
@Diolor issue is in `ImageCaptureAction#getPhoto` - for some reason `countDownLatch` is never actually counted down. I suspect that it might be because image becomes available before listener is registered and therefore `onImageAvailable` is not called.

**Comment by dmitry-zaitsev** [comment]
Fixed now.
