### ISSUE TITLE
Onstart from onstop ,The camera screen is blank

### ISSUE THREAD

**Issue by dyfan** [Fotoapparat/Fotoapparat#65]
![image](https://user-images.githubusercontent.com/15817271/28620994-ffa82a54-7241-11e7-8ca9-ab7ead3c17fa.png)
Onstart from onstop ,The camera screen is blank,click take a picture crash

**Comment by dmitry-zaitsev** [comment]
It looks like Google guys have the same issue: https://github.com/google/cameraview/pull/105

**Comment by dmitry-zaitsev** [comment]
It is presumably fixed now and will be a part of 1.3.0.

**Comment by SumantaBee** [comment]
LoL. This points to another defect which is closed by pointing back to this defect.

**Comment by shtolik** [comment]
I still have this error for some user while using 1.3.0. So it's not fixed:(
